CREATE TABLE GeoNames (
  geonameid         int,
  name              varchar(200),
  asciiname         varchar(200),
  alternatenames    varchar(10000),
  latitude          dec,
  longitude         dec,
  feature_class     char(1),
  feature_code      varchar(10),
  country_code      char(2),
  cc2               varchar(200),
  admin1_code       varchar(20),
  admin2_code       varchar(80),
  admin3_code       varchar(20),
  admin4_code       varchar(20),
  population        int,
  elevation         int,
  dem               int,
  timezone          varchar(40),
  modification_date datetime
);
