# Generated by Django 4.1.1 on 2022-10-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api', '0002_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(blank=True, to='drf_api.project'),
        ),
    ]
